### ISSUE TITLE
Start on Cloud Foundry fails when explicitely selecting java_buildpack

### ISSUE THREAD

**Issue by berndgoetz** [making/blackhole#3]
Our Cloud Foundry setup contains liberty_buildpack and java_buildpack. When I don't define any buildpack in my manifest, the liberty_buildpack is chosen, the IBM Java 8 is selected and the application is able to start up.

However, when I explicitely switch to java_buildpack in the manifest below, the start fails with the following message 

```
   2019-04-13T18:54:48.03+0200 [CELL/0] OUT Starting health monitoring of container
   2019-04-13T18:54:48.15+0200 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx12M
   2019-04-13T18:54:49.11+0200 [APP/PROC/WEB/0] OUT Exit status 137
   2019-04-13T18:54:49.11+0200 [CELL/SSHD/0] OUT Exit status 0
   2019-04-13T18:54:49.77+0200 [API/0] OUT Process has crashed with type: "web"
```

Here's the manifest.mf file:

```
applications:
- name: blackhole
  memory: 64M
  path: target/blackhole-1.0.0-SNAPSHOT.jar
  routes:
    - route: blackhole.ourcfdomain.com
  buildpack: java_buildpack
  env:
    JAVA_OPTS: '-XX:MaxMetaspaceSize=24M -XX:ReservedCodeCacheSize=16M -XX:CompressedClassSpaceSize=8M -XX:MaxDirectMemorySize=8M -Xss512k'
    JBP_CONFIG_OPEN_JDK_JRE: '[memory_calculator: {stack_threads: 8}, jre: {version: 11.+}]'
```

The Java buildpack version is 4.17.2.

What is going on here? Thanks.

**Comment by berndgoetz** [comment]
I've created https://github.com/cloudfoundry/java-buildpack/issues/720 now.

**Comment by making** [comment]
Did you try increasing memory?

**Comment by making** [comment]
It works for me on both PWS and PAS but may not work on your environment.

**Comment by berndgoetz** [comment]
> 
> 
> Did you try increasing memory?

Well, I wanted to see if a simple service like this can run with only 64M of allocated container memory. And you proved it to be working, so I wanted to reproduce myself but I can't. 

I'm running it on the [Swisscom Application Cloud](https://developer.swisscom.com/), btw.

**Comment by making** [comment]
64MB is not enough, for long running. It frequently crashes as code caches,  metaspace and compress code spaces grow.

128MB works for your env?

**Comment by berndgoetz** [comment]
> 
> 
> It works for me on both PWS and PAS but may not work on your environment.

I know PWS at https://run.pivotal.io/ but what is PAS? You own instance?

And what Java buildpack version are you running? Thanks.

**Comment by making** [comment]
PAS stands for "Pivotal Application Service".

I don't remember versions since I didn't specify the buildpack (using latest on the platfrom).
